---
name: fief
on:
  schedule:
    - cron: "13 4 * * *"
concurrency:
  group: fief
  cancel-in-progress: true
jobs:
  fief:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install fief
      - run: |
          fief --token ${{ secrets.TOKEN }} --delay 1000 \
            --include objectionary/* \
            --include polystat/* \
            --exclude objectionary/.github \
            --exclude polystat/.github \
            --to html
      - run: mkdir gh-pages
      - run: cp html/index.html gh-pages/fief.html
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
