name: releases

on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
env:
  is_exist: 'false'

jobs:
  check-releases:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: install pdd
        run: gem install pdd
      - name: pull releases
        run: |
          python3 py/auto_pull.py
#      - name: Import GPG key
#        uses: crazy-max/ghaction-import-gpg@v6
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
##          passphrase: ${{ secrets.PASSPHRASE }}
#          git_user_signingkey: true
#          git_commit_gpgsign: true
#          git_push_gpgsign: ""
      - name: Check if branch exists
        run: |
          python3 py/is_branch_exist.py ${{ env.eo_lib_version }}
          echo "is_exist: ${{ env.is_exist }}"
  create-pull-request:
    if: ${{ env.is_exist == 'false' }}
    needs: check-releases
    runs-on: ubuntu-22.04
    steps:
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN }}
          committer: yegor256 <yegor256@gmail.com>
          commit-message: New release for ${{ env.eo_lib_version }}
          title: New release for ${{ env.eo_lib_version }}
          body: New release for ${{ env.eo_lib_version }}
          base: master
          branch: update-${{ env.eo_lib_version }}
          delete-branch: true
